#! /bin/bash
tmux has-session-t dev
if [ $? != 0 ]
then
  tmux new-session -s dev -n editor -d
  tmux send-keys -t dev 'vim' C-m
  tmux split-window -v -t dev
  tmux send-keys -t dev:1.2 'test -d .git && gsta && gup && gstp' C-m
  tmux select-layout -t dev main-vertical
  tmux new-window -n console -t dev
  tmux select-window -t dev:1
fi
tmux attach -t dev
