brew install vim
brew install ab
brew install docker-machine
brew install jq
brew install go
brew install graphviz
brew install highlight
brew install lynx
brew install node
brew install tree
brew install wget
brew install watch
brew install terraform
brew install mono
brew install gource
